export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const LOGIN_RESPONSE_SUCCESS = "LOGIN_RESPONSE_SUCCESS";
export const LOGIN_RESPONSE_FAILURE = "LOGIN_RESPONSE_FAILURE";
export const CREATE_ORGANISATION = "CREATE_ORGANISATION";
export const GET_ORGANISATION_LIST = "GET_ORGANISATION_LIST";
