export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const CHNAGE_SUCCESSFUL_CREATION = "CHNAGE_SUCCESSFUL_CREATION";
export const SIGNUP = "SIGNUP";
export const LOGIN_RESPONSE_SUCCESS = "LOGIN_RESPONSE_SUCCESS";
export const LOGIN_RESPONSE_FAILURE = "LOGIN_RESPONSE_FAILURE";
